version: "3"

services:
  
  react:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: react
    user: "node"
    working_dir: /usr/src/app
    container_name: react
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - app

networks:
  app:
    driver: bridge

